#
# Sample scripts for 'Posh-Shodan'
#
# Generated by: Dan Borges <ahhh.db@gmail.com>
#
# Generated on: 11/29/2015
#
# Description: Sample output for saving and manipulating data pulled from Shodan
#

## Functions
# Save output in different formats

# Save Results as Json
function Output-JSON($results, $filename)
{
    $results.matches | ConvertTo-Json > "$($filename).json"
    Write-Host "Full result set saved to: $($filename).json"
}

function Output-XML($results, $filename)
{
    $results.matches | Export-Clixml "$($filename).xml"
    Write-Host "Full result set saved to: $($filename).xml"
}

function Output-CSV($results, $filename)
{
    $results.matches | ConvertTo-Csv > "$($filename).csv"
    Write-Host "Full result set saved to: $($filename).csv"
}

function Output-Text($results, $filename)
{
    $results.matches > "$($filename).txt"
    Write-Host "Full result set saved to: $($filename).txt"
}

function Output-HTML($results, $filename)
{
    $results.matches | ConvertTo-Html > "$($filename).html"
    Write-Host "Full result set saved to: $($filename).html"
}

function Output-Table($results, $filename)
{
    $results.matches | Format-Table > "$($filename).txt"
    Write-Host "Full result set saved to: $($filename).txt"
}

$Query = Read-Host -Prompt 'Enter a simple query: '
$filename = Read-Host -Prompt 'Name of output file: '
Write-Host 'Select the file output format:'
Write-Host '1) JSON'
Write-Host '2) XML'
Write-Host '3) CSV'
Write-Host '4) TEXT'
Write-Host '5) HTML'
Write-Host '6) Table'
$Output = Read-Host -Prompt 'Your output selection: '

# Make query
$results = Search-ShodanHost -Query "$($Query)"

# Switch on way to save results
switch($Output)
{
    1{Output-JSON $results $filename}
    2{Output-XML $results $filename}
    3{Output-CSV $results $filename}
    4{Output-Text $results $filename}
    5{Output-HTML $results $filename}
    6{Output-Table $results $filename}
}
