#
# Sample scripts for 'Posh-Shodan'
#
# Generated by: Dan Borges <ahhh.db@gmail.com>
#
# Generated on: 11/28/2015
#
# Description: Simple cmd queries and parsed responses, don't use any tokens on advanced searches
#

## Functions
# Parse our results in a cleaner way
function Write-SimpleParse
{
    [CmdletBinding()]
    Param
    (
        [Parameter(Mandatory=$true, Position=0)]
        $results
    )
    
    foreach ($result in $($results.matches | Select -First $Quantity))
    {
        Write-Output ""
        Write-Output "IP: $($result.ip_str)"
        Write-Output "Port: $($result.port)"
        Write-Output "Domains: $($result.domains)"
        Write-Output "Location: $($result.location)"
        Write-Output "Data: $($result.data)"
        Write-Output ""
    }
}

$Query = Read-Host -Prompt 'Your simple search query: '
$Quantity = Read-Host -Prompt 'Amount of results to return: '

# Make our simple query
$results = Search-ShodanHost -page 1 -Query "$($Query)"

# Dump our results
#$results.matches | Select -First $($Quantity)

# Pretty print our results
Write-SimpleParse $results
